-- ════════════════════════════════════════════════════════════════════════════
-- FIX : table chrono_scoreur_scores (Scoreur Speedrun)
-- ════════════════════════════════════════════════════════════════════════════
-- Symptôme : erreurs HTTP 400 sur POST /rest/v1/chrono_scoreur_scores
--            → "Erreur DB (table chrono_scoreur_scores)", aucun classement.
--
-- CAUSE RÉELLE (diagnostiquée le 31/05/2026) :
--   La table existait déjà d'une ancienne version avec joueur_id en type BIGINT.
--   L'app envoie un UUID (ex: 6db6b5b2-...). Postgres refuse :
--     code 22P02 : invalid input syntax for type bigint: "6db6b5b2-..."
--   Le SELECT marchait (lecture sans contrôle de type) mais tout INSERT échouait.
--   ADD COLUMN IF NOT EXISTS ne corrige PAS un type de colonne existant → il faut
--   recréer la table. Elle a été vérifiée VIDE (0 ligne) → recréation sans perte.
--
-- À EXÉCUTER dans : Supabase Dashboard > SQL Editor > New query > Run.
-- ════════════════════════════════════════════════════════════════════════════

-- Table vérifiée vide → on la recrée proprement avec les bons types (joueur_id = uuid)
drop table if exists public.chrono_scoreur_scores cascade;

create table public.chrono_scoreur_scores (
  id            bigint generated by default as identity primary key,
  joueur_id     uuid,                            -- ⬅️ uuid (et non bigint)
  joueur_pseudo text,
  date_jour     date,
  statut        text    default 'abandonne',     -- 'termine' | 'abandonne'
  score_initial integer default 501,
  nb_volees     integer default 0,
  erreurs       integer default 0,
  volees        jsonb   default '[]'::jsonb,
  temps_ms      integer default 0,
  rewarded      boolean default false,
  created_at    timestamptz default now()
);

create index idx_scoreur_date  on public.chrono_scoreur_scores (date_jour);
create index idx_scoreur_temps on public.chrono_scoreur_scores (date_jour, temps_ms);

-- RLS : l'app utilise la clé anon → lecture/écriture publiques
alter table public.chrono_scoreur_scores enable row level security;
create policy "scoreur_select_public" on public.chrono_scoreur_scores for select using (true);
create policy "scoreur_insert_public" on public.chrono_scoreur_scores for insert with check (true);
create policy "scoreur_update_public" on public.chrono_scoreur_scores for update using (true) with check (true);

-- Force PostgREST à recharger son cache de schéma
notify pgrst, 'reload schema';
