-- ════════════════════════════════════════════════════════════════════════════
-- FIX : table chrono_scoreur_scores (Scoreur Speedrun)
-- ════════════════════════════════════════════════════════════════════════════
-- Symptôme : erreurs HTTP 400 sur /rest/v1/chrono_scoreur_scores
--            → aucun classement, le joueur reste bloqué.
-- Cause    : table absente ou colonnes manquantes dans Supabase.
--
-- À EXÉCUTER dans : Supabase Dashboard > SQL Editor > New query > Run.
-- 100 % idempotent : sans danger même si la table existe déjà (ne supprime rien).
-- ════════════════════════════════════════════════════════════════════════════

-- 1) Crée la table si elle n'existe pas (mêmes colonnes que chrono_finish_scores)
create table if not exists public.chrono_scoreur_scores (
  id            bigint generated by default as identity primary key,
  joueur_id     uuid,
  joueur_pseudo text,
  date_jour     date,
  statut        text    default 'abandonne',   -- 'termine' | 'abandonne'
  score_initial integer default 501,
  nb_volees     integer default 0,
  erreurs       integer default 0,
  volees        jsonb   default '[]'::jsonb,
  temps_ms      integer default 0,
  rewarded      boolean default false,
  created_at    timestamptz default now()
);

-- 2) Ajoute les colonnes manquantes si la table existait déjà en version partielle
alter table public.chrono_scoreur_scores add column if not exists joueur_id     uuid;
alter table public.chrono_scoreur_scores add column if not exists joueur_pseudo text;
alter table public.chrono_scoreur_scores add column if not exists date_jour     date;
alter table public.chrono_scoreur_scores add column if not exists statut        text    default 'abandonne';
alter table public.chrono_scoreur_scores add column if not exists score_initial integer default 501;
alter table public.chrono_scoreur_scores add column if not exists nb_volees     integer default 0;
alter table public.chrono_scoreur_scores add column if not exists erreurs       integer default 0;
alter table public.chrono_scoreur_scores add column if not exists volees        jsonb   default '[]'::jsonb;
alter table public.chrono_scoreur_scores add column if not exists temps_ms      integer default 0;
alter table public.chrono_scoreur_scores add column if not exists rewarded      boolean default false;
alter table public.chrono_scoreur_scores add column if not exists created_at    timestamptz default now();

-- 3) Index pour des classements rapides par jour
create index if not exists idx_scoreur_date  on public.chrono_scoreur_scores (date_jour);
create index if not exists idx_scoreur_temps on public.chrono_scoreur_scores (date_jour, temps_ms);

-- 4) RLS : l'app utilise la clé anon → on autorise lecture/écriture publiques
alter table public.chrono_scoreur_scores enable row level security;

drop policy if exists "scoreur_select_public" on public.chrono_scoreur_scores;
drop policy if exists "scoreur_insert_public" on public.chrono_scoreur_scores;
drop policy if exists "scoreur_update_public" on public.chrono_scoreur_scores;

create policy "scoreur_select_public" on public.chrono_scoreur_scores
  for select using (true);
create policy "scoreur_insert_public" on public.chrono_scoreur_scores
  for insert with check (true);
create policy "scoreur_update_public" on public.chrono_scoreur_scores
  for update using (true) with check (true);

-- 5) Force PostgREST à recharger son cache de schéma (sinon 400 PGRST204 persiste)
notify pgrst, 'reload schema';
